/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-secondary-fixed-variant": "#474747",
                "error": "#ba1a1a",
                "on-secondary-fixed": "#1b1b1b",
                "inverse-primary": "#e3c600",
                "on-tertiary": "#ffffff",
                "on-primary-fixed-variant": "#524600",
                "secondary": "#5e5e5e",
                "primary-fixed": "#ffe24b",
                "on-tertiary-container": "#be212a",
                "on-error-container": "#93000a",
                "tertiary-fixed": "#ffdad7",
                "primary-container": "#ffde03",
                "surface-variant": "#e2e2e2",
                "primary": "#6d5e00",
                "tertiary-container": "#ffd5d2",
                "tertiary": "#b81d27",
                "outline": "#7d775f",
                "on-error": "#ffffff",
                "on-tertiary-fixed-variant": "#930015",
                "surface-container-highest": "#e2e2e2",
                "primary-fixed-dim": "#e3c600",
                "inverse-surface": "#2f3131",
                "surface-container-high": "#e8e8e8",
                "inverse-on-surface": "#f0f1f1",
                "surface-bright": "#f9f9f9",
                "on-primary-fixed": "#211b00",
                "on-background": "#1a1c1c",
                "secondary-container": "#e2e2e2",
                "surface": "#f9f9f9",
                "secondary-fixed-dim": "#c6c6c6",
                "surface-tint": "#6d5e00",
                "outline-variant": "#cfc6ab",
                "on-secondary-container": "#646464",
                "background": "#f9f9f9",
                "surface-container": "#eeeeee",
                "on-surface-variant": "#4c4732",
                "tertiary-fixed-dim": "#ffb3ae",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f3f3f4",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#e2e2e2",
                "on-primary": "#ffffff",
                "error-container": "#ffdad6",
                "on-surface": "#1a1c1c",
                "on-tertiary-fixed": "#410004",
                "surface-dim": "#dadada",
                "on-primary-container": "#716200"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Work Sans", "sans-serif"],
                "label": ["Work Sans", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
        },
    },
    plugins: [
        require('@tailwindcss/container-queries')
    ],
}
